# Generated by Django 4.2 on 2023-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
